import { RequestedTopicType } from '@/lib/types/requestedTopicType';

export const requestedTopicData: RequestedTopicType[] = [
  {
    categoryEngName: 'culture',
    categoryKorName: '문화',
    title: '지역 문화 행사 안내',
    description: '이번 주말에 진행되는 지역 문화 행사를 안내드립니다.',
    createdDate: '2024-10-26',
    ownerId: 2,
    ownerNickname: '문화팀',
    isAnonymous: false,
    isExposed: true,
  },
  {
    categoryEngName: 'life',
    categoryKorName: '일상생활',
    title: '일상생활 팁 공유',
    description: '일상생활을 더 편리하게 만들어줄 유용한 팁을 공유합니다.',
    createdDate: '2024-10-27',
    ownerId: 3,
    ownerNickname: '일상고수',
    isAnonymous: true,
    isExposed: false,
  },
  {
    categoryEngName: 'place',
    categoryKorName: '장소',
    title: '서울의 숨겨진 명소 추천',
    description: '잘 알려지지 않은 서울의 멋진 장소를 소개합니다.',
    createdDate: '2024-10-20',
    ownerId: 4,
    ownerNickname: '여행자',
    isAnonymous: false,
    isExposed: true,
  },
  {
    categoryEngName: 'music',
    categoryKorName: '음악',
    title: '이번 주 추천 음악',
    description: '가을에 어울리는 음악 리스트를 공유합니다.',
    createdDate: '2024-10-21',
    ownerId: 5,
    ownerNickname: '음악사랑',
    isAnonymous: false,
    isExposed: true,
  },
  {
    categoryEngName: 'movie_drama',
    categoryKorName: '영화/드라마',
    title: '최근 본 영화/드라마 리뷰',
    description: '최근에 감상한 영화와 드라마에 대한 리뷰를 남깁니다.',
    createdDate: '2024-10-22',
    ownerId: 6,
    ownerNickname: '영화광',
    isAnonymous: false,
    isExposed: true,
  },
  {
    categoryEngName: 'book',
    categoryKorName: '도서',
    title: '이번 달 추천 도서',
    description: '이달의 추천 도서를 소개합니다. 책을 좋아하는 분들께 추천!',
    createdDate: '2024-10-23',
    ownerId: 7,
    ownerNickname: '책사랑',
    isAnonymous: false,
    isExposed: true,
  },
  {
    categoryEngName: 'animal_plant',
    categoryKorName: '동식물',
    title: '우리 집 반려동물 소개',
    description: '우리 집 귀여운 반려동물을 소개합니다. 사진 포함!',
    createdDate: '2024-10-24',
    ownerId: 8,
    ownerNickname: '동물사랑',
    isAnonymous: true,
    isExposed: false,
  },
  {
    categoryEngName: 'etc',
    categoryKorName: '기타',
    title: '기타 자유 주제',
    description: '어떤 주제든 자유롭게 이야기 나누는 공간입니다.',
    createdDate: '2024-10-25',
    ownerId: 9,
    ownerNickname: '자유인',
    isAnonymous: false,
    isExposed: true,
  },
];
